# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/harry_potter_db
spring.datasource.username=sergio_user
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Keep schema managed by SQL scripts/migrations
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
